### ISSUE TITLE
  raise NotImplementedError, 'emit must be implemented ' SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lanyan520** [ForeignGods/ComfyUI-Mana-Nodes#16]
error message:

Collecting logging (from -r requirements.txt (line 10))
  Using cached logging-0.4.9.6.tar.gz (96 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 22, in <module>
          from .dist import Distribution
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 12, in <module>
          import logging
        File "/private/var/folders/xv/rmnk14792yb52bmmqqqt8vmc0000gn/T/pip-install-q5hkc71g/logging_b87396e952c24f2f8ffab55c4ca0a903/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I can't import logging, how can I solve it

**Comment by lanyan520** [comment]
> Just removed 'logging' from the requirements.txt file. I have no idea why I included it there, since logging is a standard library module in Python and does not need to be installed via pip. Thanks for the feedback. Use the updated requirements.txt and let me know if this resolved your issue?

No, the installation still reports the same error, and the node cannot be loaded

**Comment by ForeignGods** [comment]
Try using this command with the option to avoid using cached packages.

`.\python_embed\python.exe -s -m pip install --no-cache-dir -r requirements.txt --user`

Also make sure you're using the requirements.txt where I removed the logging.

In your error message it seems to say it's using the cached logging you installed previously.

`Collecting logging (from -r requirements.txt (line 10))
Using cached logging-0.4.9.6.tar.gz (96 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error`

**Comment by lanyan520** [comment]
> Try using this command with the option to avoid using cached packages.
> 
> `.\python_embed\python.exe -s -m pip install --no-cache-dir -r requirements.txt --user`
> 
> Also make sure you're using the requirements.txt where I removed the logging.
> 
> In your error message it seems to say it's using the cached logging you installed previously.
> 
> `Collecting logging (from -r requirements.txt (line 10)) Using cached logging-0.4.9.6.tar.gz (96 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error`

Thank you, the node has been successfully imported

But there is a new issue: when this project is enabled, opening the website at 127.0.0.1:8188 will result in an error when loading any node, and it will wait for about 1 minute to recover. Removing this project and loading it directly will be fine
However, I am no longer concerned about this situation, as long as it satisfies my learning needs
